# Generated by Django 2.2.4 on 2019-08-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0005_auto_20190811_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houselistings',
            name='MSZoning',
        ),
        migrations.RemoveField(
            model_name='houselistings',
            name='Neighborhood',
        ),
    ]
